copyright: 'Copyright &copy; 2023 Made with ♥ by <a href="https://lrmn.is-a.dev/">L RMN</a>'
site_description: 'Personal website of L RMN'
site_author: 'L RMN'
site_name: 'L RMN'
site_url: 'https://lrmn.is-a.dev/docs'
site_dir: 'public'

# repository edit info
edit_uri: edit/main/docs/
repo_name: lrmn7/docs
repo_url: https://github.com/lrmn7/docs

# Table of content
# Table of content
nav:
  - 🚀Home: index.md
  - 🐵Profile: profile.md
  - ✍🏻Blog:
    - ... | articles/*/*
  - 🖥️Projects:
    - ... | projects/*/*
  - ❤️Donate: donation.md





theme:
  name: material
  custom_dir: overrides
  logo: assets/images/favicon-32x32.png
  favicon: assets/images/favicon.ico
  font:
    text: Noto Sans
    code: Fira Code
  palette:
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - navigation.top

plugins:
  - search
  - mermaid2
  #- git-revision-date-localized:
      #fallback_to_build_date: false
  - macros
  - mkdocs-jupyter:
      include_source: True
  - awesome-pages

markdown_extensions:
  - tables
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - attr_list
  - md_in_html
  - meta

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lrmn7
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/romanroman.nya
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/romanromannya
    - icon: fontawesome/brands/pinterest
      link: https://id.pinterest.com/romanromannya
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@LRMN_vp
  generator: false
      
  analytics:
    provider: google
    property: G-SDQ15H0726

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/extra.css
